---
- name: Configure and start CloudWatch Agent
  hosts: linux
  gather_facts: no
  tasks:
  - name: Create CloudWatch Agent configuration file
    lineinfile:
    #push json from local
      path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      state: present
      line: '{ "metrics": { "namespace": "MyApp/Metrics" } }'

  - name: Start CloudWatch Agent
    service:
      name: amazon-cloudwatch-agent
      state: started
